### ISSUE TITLE
Conflicts with latest Xamarin.Google.iOS.MobileAds on iOS

### ISSUE THREAD

**Issue by AndreasReitberger** [GalaxiaGuy/GoogleUserMessagingPlatform#4]
Hi,
first thank you for making this addon!
It was working fine for me, however once I updated Xamarin.Google.iOS.MobileAds to the version "7.66.0"
Visual Studio is thowing an error when I try to build for iOS.

Something like "Cannot include different versions of GoogleUserMessagingPlatform".
https://github.com/xamarin/GoogleApisForiOSComponents/commit/9561e99f0afb239b24dd8580bcb33eca6715838a

The new version includes 1.1.0 of GoogleUserMessagingPlatform

**Comment by GalaxiaGuy** [comment]
It looks like they have embedded a GoogleUserMessagingPlatform binding into GoogleMobileAds 7.66.0. I could probably deal with it by taking a dependency on GoogleMobileAds (which is probably fine since 99% of the time that's what people using UMP will need).

**Comment by AndreasReitberger** [comment]
> It looks like they have embedded a GoogleUserMessagingPlatform binding into GoogleMobileAds 7.66.0. I could probably deal with it by taking a dependency on GoogleMobileAds (which is probably fine since 99% of the time that's what people using UMP will need).

Sounds like a plan to me ;) Thanks for your help!
